### ISSUE TITLE
Add disclaimers and restrictions to index and detail views

### ISSUE THREAD

**Issue by cjavilla-stripe** [stripe-samples/accept-a-payment#2] opened 2021-01-28 19:13 UTC
We need to communicate restrictions like (don't really need to cover all, but most would be good): 

- only works for Stripe accounts in MY 
- only works with X and Y currencies
- only works for X currencies on Stripe accounts in X countries
- only works with https
- only works with specific MCC

**Comment by Cordelro86** [comment] 2021-08-23 08:08
X

**Comment by Cordelro86** [comment] 2021-08-23 08:08
X

**Comment by Cordelro86** [comment] 2021-08-23 08:09
X

**Comment by Cordelro86** [comment] 2021-08-23 08:09
X

**Comment by Cordelro86** [comment] 2021-08-23 08:09
Payment

**Comment by Cordelro** [comment] 2021-10-21 08:48
#323

**Comment by wendylove14700** [comment] 2022-04-30 14:11
> #323 

ch_3KtgKtFc7yM6jura1Kl3oAhG

**Comment by Abrdjalw** [comment] 2022-07-11 05:26
https://github.com/stripe-samples/accept-a-payment/issues/2#issuecomment-903539623

**Comment by Abrdjalw** [comment] 2022-07-11 11:35
#1042

**Comment by Abrdjalw** [comment] 2022-07-11 11:35
Duplicate of #

**Closed as completed** 2022-07-11 13:50 UTC
